hostUrl: "http://127.0.0.1" #Host url which is used by twilio for voice and included in text and email
localAudioAlert: true #Set off a local alert tone and bridge audio for 25 seconds from alert
disableAlerting: false #Disable all alerting and make the software just decode and encode tones
smallScreen: true #Variable made for RPI screens. Will set the size to 480x320
softwareDirectory: "C:/Users/user_name/ToneToneAlert/" #Full path

socketLabs:
  enable: false
  serverId: 12345
  clientId: ""
  from: "test@example.com"

twilio:
  enable: false
  accountSid: ""
  authToken: ""
  from: "+1xxxXXXxxxx"

discord:
  enable: false
  url: "" #Discord webhook url

serial: #I'm not really sure what serial devices are supported
  enable: false
  port: "COM1"

smartHome: #Currently only Tp-Link Kasa switches are supported
  enable: false